require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/internal/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.2

Rails:
  Enabled: true

# Metrics/LineLength:
#   Max: 120

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Exclude:
  - 'spec/**/*'

Style/DoubleNegation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/views/**/*'

# Pending https://github.com/bbatsov/rubocop/pull/3250
RSpec/InstanceVariable:
  Exclude:
    - 'spec/controllers/spotlight/confirmations_controller_spec.rb'
    - 'spec/views/spotlight/searches/_search.html.erb_spec.rb'

Metrics/AbcSize:
  Max: 20

Metrics/ModuleLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - 'app/models/spotlight/resource.rb'
    - 'lib/generators/spotlight/**/*' # Generators tend to have longer class lengths due to their lengthy public API
